### ISSUE TITLE
Some grammar usability issues

### ISSUE THREAD

**Issue by ahlinc** [amaanq/tree-sitter-kdl#1]
<details><summary>Screenshot</summary>

![Screenshot from 2023-01-27 13-43-08](https://user-images.githubusercontent.com/14666676/215078316-cfa58524-ef21-4d0b-9455-6efdbaf9080d.png)
</details>

**Notes:**
* A link in readme points to `tree-sitter` but I suppose it would be better to point on https://kdl.dev/
* The grammar on above screenshot captures a lot of `" "` and `"\n"` nodes that would be better to don't exists in a tree.
* It makes sense in the `string` nodes to add an additional anonymous or named node to capture inner text.

A customized _(but yet unpublished)_ version of the tree-sitter CLI that behaves like on above screenshot can be installed with the `cargo` like:
`cargo install --git https://github.com/ahlinc/tree-sitter --branch alpha`

**Comment by amaanq** [comment]
Fixed the readme, for 2 should I inline those captures? or how would that work? for whitespace I mostly followed kdl's spec since kdl has funky inline comments to comment out parts of valid code but not everything, e.g.
![image](https://user-images.githubusercontent.com/29718261/215081247-32d3c4bb-ede7-4f6d-966b-e8fb91c76cc6.png)

for the string issue, can I change it like so?

```js
_escaped_string: ($) => seq('"', repeat(choice($._escape, /[^"]/)), '"'),
```

to

```js
_escaped_string: ($) => seq('"', alias(repeat(choice($._escape, /[^"]/)), $._string_content), '"'),
```

**Comment by amaanq** [comment]
Wanted to add I did notice it took *quite* a while for tree-sitter to parse a file at first, that likely does stem from this excessive whitespace capturing, so I would love to hear what solutions you might have for that!

**Comment by ahlinc** [comment]
> Wanted to add I did notice it took _quite_ a while for tree-sitter to parse a file at first, that likely does stem from this excessive whitespace capturing, so I would love to hear what solutions you might have for that!

Tree-sitter CLI hiddenly compiles an `*.so` library on the `parse` command after every change of a grammar by `tree-sitter generate` command, that may be a reason for a longer starting of parsing.

**Comment by amaanq** [comment]
> > Wanted to add I did notice it took _quite_ a while for tree-sitter to parse a file at first, that likely does stem from this excessive whitespace capturing, so I would love to hear what solutions you might have for that!
> 
> Tree-sitter CLI hiddenly compiles an `*.so` library on the `parse` command after every change of a grammar by `tree-sitter generate` command, that may be a reason for a longer starting of parsing.

Yeah I know about that, I worded that poorly so I'll clarify; I wrote a few other parsers and this one feels like it takes *significantly* longer to run on a file at first compared to those. While it might just be an extra second or two, the difference is relatively large.

**Comment by ahlinc** [comment]
> Yeah I know about that, I worded that poorly so I'll clarify; I wrote a few other parsers and this one feels like it takes _significantly_ longer to run on a file at first compared to those. While it might just be an extra second or two, the difference is relatively large.

Sorry, I don't know what to say without reproducible example.

**Comment by amaanq** [comment]
> > Yeah I know about that, I worded that poorly so I'll clarify; I wrote a few other parsers and this one feels like it takes _significantly_ longer to run on a file at first compared to those. While it might just be an extra second or two, the difference is relatively large.
> 
> Sorry, I don't know what to say without reproducible example.

Hmm, either way do you know of a solution to get rid of or "inline" the whitespace capture? Inlining the rules didn't help

**Comment by ahlinc** [comment]
I've pushed a PR with fixes.

> Hmm, either way do you know of a solution to get rid of or "inline" the whitespace capture? Inlining the rules didn't help

The solution is to use `/regex/` like terminals instead of `"text"` terminals because text terminals creates anonymous nodes while regex terminals by default don't create any tree visible nodes but may be made visible by applying aliases.

**Comment by ahlinc** [comment]
@amaanq I've added `examples/` folder with official snippets because it makes easy to test against all snippets with a one command: 
`ts p -oct examples/*`

**Comment by amaanq** [comment]
> I've pushed a PR with fixes.
> 
> > Hmm, either way do you know of a solution to get rid of or "inline" the whitespace capture? Inlining the rules didn't help
> 
> The solution is to use `/regex/` like terminals instead of `"text"` terminals because text terminals create anonymous nodes while regex terminals by default don't create any tree visible nodes but may be made visible by applying aliases.

Thank you very much! That totally makes sense, I just thought it'd look better  to use text instead of regexes everywhere for those specific 1 "char" cases. Never knew it could affect the visible nodes like that, but that makes sense

**Comment by amaanq** [comment]
> @amaanq I've added `examples/` folder with official snippets because it makes easy to test against all snippets with a one command: 
> `ts p -oct examples/*`

That's great! I love your cli fork for extensively showing nodes, that will be super helpful in the future. Is there a reason parts if not all of your changes can't be merged upstream?

**Comment by amaanq** [comment]
> > That's great! I love your cli fork for extensively showing nodes, that will be super helpful in the future. Is there a reason parts if not all of your changes can't be merged upstream?
> 
> You welcome! I was happy to help :smiley: 
> 
> There are many corner cases currently unhandled in the fork, but I hope I'll find a time to finish all that in a month or two.
> You may found more info about custom CLI in a [Discord channel](https://github.com/tree-sitter/tree-sitter/discussions/2027).

Seems like the discord invite there is expired, do you think you can generate a new one for me?

**Comment by ahlinc** [comment]
> Seems like the discord invite there is expired, do you think you can generate a new one for me?

I've generated unexpirable link, try the next one: https://discord.gg/w7nTvsVJhm
