### ISSUE TITLE
Number highlight doesn't work?

### ISSUE THREAD

**Issue by Samonitari** [amaanq/tree-sitter-kdl#8]
Hi!

Thanks for the grammar, first of all!
I am using [helix editor](https://github.com/helix-editor/helix), and tried your proj instead of [the other, seemingly unmaintained KDL grammar](https://github.com/Unoqwy/tree-sitter-kdl) that has been shipping with helix - your project is a promising, new option...

My first impressions are: it is better, and more correct - I mean your project has more LoC, so obviously it must be better 🤣 

A little, specific example to be a bit more serious - yours is the new, which doesn't get confused by the escaped `"` in zellij's conf:
![Old_1](https://user-images.githubusercontent.com/15932551/224258238-2d4ef06a-e7ae-4018-a6a6-e40acf1da182.jpg)
![New_1](https://user-images.githubusercontent.com/15932551/224258247-7d8f8e0d-d7b6-4e51-94bc-e17074f92c3e.jpg)

OTOH, a further bit down, your grammar - or to be precise, helix with your grammar - doesn't colour numbers:
![Old_2](https://user-images.githubusercontent.com/15932551/224259031-b1c2614f-4192-4c5e-a25a-9f7dae711f88.jpg)
![New_2](https://user-images.githubusercontent.com/15932551/224259035-43be5153-2a4f-4bab-b640-c4bd3865be43.jpg)

As a side note, I started to write a grammar for caddy, and your project was one of the templates I was coming back to.
I cant' get `@number` in highlights.scm to work in my projects neither, although the old KDL grammar - and other supplied grammars - **do** use that *highlight name* successfully....

**Comment by amaanq** [comment]
> My first impressions are: it is better, and more correct - I mean your project has more LoC, so obviously it must be better :rofl: 

Haha, maybe the more grammars I have the better they are (check [here](https://github.com/amaanq#tree-sitter) ;) )

Helix flips the query precedence atm (but we are helping them migrate to Neovim/recommended standard soon, topic for another day), are you using my queries verbatim here? In Helix, first wins not last so play around with that if so, if not, send some code but I believe it works fine for me..

**Comment by Samonitari** [comment]
> Helix flips the query precedence atm (but we are helping them migrate to Neovim/recommended standard soon, topic for another day, and after that I will suggest/help them to use any languages they are missing that I have grammars for)

Thanks, that's good to hear. I was going to open a PR to make it use your KDL grammar, but I guess, you should be the one...

> In Helix, first wins not last so play around with that if so, if not, send some code but I believe it works fine for me..

Okay, that should solve it.

Side note: My caddyfile grammar is still very alpha (`token` restrictions on terminal/anonymous nodes makes it more difficult than it's supposed to be), but it's coming together nevertheless, glad that nginx is going to be supported too (on my private server ditched it, but at work I'll probably need it).
